How to perform logistic regression
e.g: based on the SAT score predict which gender (m/f) have higher probability to admitted

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
sns.set()

In [33]:
data_row=pd.read_csv('2.02.+Binary+predictors.csv')#read the data set
data_row.head()


SAT Admitted  Gender
0  1363       No    Male
1  1792      Yes  Female
2  1954      Yes  Female
3  1653       No    Male
4  1593       No    Male

maping catagorical data and change the values to 1 and 0 , for perform logistic regression

In [34]:
data=data_row.copy()
data['Admitted']=data['Admitted'].map({'Yes':1,'No':0})
data['Gender']=data['Gender'].map({'Female':1,'Male':0})
data.head()

SAT  Admitted  Gender
0  1363         0       0
1  1792         1       1
2  1954         1       1
3  1653         0       0
4  1593         0       0

In [35]:
y=data['Admitted']#independent or target variable
x1=data[['SAT','Gender']]#inputs
x=sm.add_constant(x1)#add constant will add dummy constants with 1.0 value


C:\Users\AMAL BABU\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


In [36]:
reg_log=sm.Logit(y,x)#regression
result_log=reg_log.fit()
result_log.summary()

Optimization terminated successfully.
         Current function value: 0.120117
         Iterations 10


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:               Admitted   No. Observations:                  168
Model:                          Logit   Df Residuals:                      165
Method:                           MLE   Df Model:                            2
Date:                Wed, 29 Dec 2021   Pseudo R-squ.:                  0.8249
Time:                        07:50:39   Log-Likelihood:                -20.180
converged:                       True   LL-Null:                       -115.26
Covariance Type:            nonrobust   LLR p-value:                 5.118e-42
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const        -68.3489     16.454     -4.154      0.000    -100.598     -36.100
SAT            0.0406      0.010      4.129      0.000       0.021       0.060
Gender         1.9449      0.846      2.299      0.022       0.287       3.603
==============================================================================

Possibly complete quasi-separation: A fraction 0.27 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [37]:
# odds_female=np.exp(2.0786)*odds_male
np.exp(1.9449)

6.992932526814459

In [38]:
#Accuracy of model

np.array(data['Admitted'])#these are the probabilities for get admitted,valu range 0-1

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [39]:
result_log.pred_table()#this is confusion matrix

array([[69.,  5.],
       [ 4., 90.]])

In [40]:
#convert this confusion matrix to pd dataframe for unersatanding
cm_df=pd.DataFrame(result_log.pred_table())
cm_df.columns=['Predicted 0','Predicate 1']
cm_df=cm_df.rename(index={0:'Actual 0',1:'Actual 1'})
cm_df
#69 observations, the model predict  0 , when the true value was 
#90 observations, the model predict  1, when the true valu is 1

Predicted 0  Predicate 1
Actual 0         69.0          5.0
Actual 1          4.0         90.0

In [41]:
#Accuracy of model (69+90)/(90+69+5+4)

cm=np.array(cm_df)
accuracy_train=(cm[0,0]+cm[1,1])/cm.sum()
accuracy_train

0.9464285714285714

In [42]:
#Testing
test=pd.read_csv('2.03.+Test+dataset.csv')
test.head()


SAT Admitted  Gender
0  1323       No    Male
1  1725      Yes  Female
2  1762      Yes  Female
3  1777      Yes    Male
4  1665       No    Male

In [43]:
test['Admitted']=test['Admitted'].map({'Yes':1,'No':0})
test['Gender']=test['Gender'].map({'Female':1,'Male':0})
test.head()

SAT  Admitted  Gender
0  1323         0       0
1  1725         1       1
2  1762         1       1
3  1777         1       0
4  1665         0       0

In [44]:
test_actual=test['Admitted']
test_data=test.drop(['Admitted'],axis=1)
test_data=sm.add_constant(test_data)
test_data.head()

C:\Users\AMAL BABU\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)


const   SAT  Gender
0    1.0  1323       0
1    1.0  1725       1
2    1.0  1762       1
3    1.0  1777       0
4    1.0  1665       0

In [45]:
# test_log=sm.Logit(test_actual,test_data)
# result_test_log=test_log.fit()
# result_test_log.summary()

In [46]:
def confusion_matrix(data,actual_values,model):
    pred_value=model.predict(data)#model is result_log
    #spesify the bins if value < 0.5 confider as 0 otherwise 1
    bins=np.array([0,0.5,1])
    #creating confusion matrix, histogram2d will compare actual values and pred_values 
    cm=np.histogram2d(actual_values,pred_value,bins=bins)[0]
    accuracy=(cm[0,0]+cm[1,1])/cm.sum()#calculating accuracy
    
    return cm,accuracy

In [47]:
cm_result=confusion_matrix(test_data,test_actual,result_log)
cm_result

(array([[ 5.,  1.],
        [ 1., 12.]]),
 0.8947368421052632)

In [48]:
cm_def=pd.DataFrame(cm_result[0])
cm_def.columns=['Predicted 0','Predicted 1']
cm_def=cm_def.rename(index={0:'Actual 0',1:'Actual 1'})
cm_def

Predicted 0  Predicted 1
Actual 0          5.0          1.0
Actual 1          1.0         12.0

In [50]:
#missclassigfication rate (1+1)/19)
cm_miss=(cm_result[0][0,1]+cm_result[0][1,0])/cm_result[0].sum()
cm_miss

0.10526315789473684